### ISSUE TITLE
[CSS] Background: url() statement badly transformed

### ISSUE THREAD

**Issue by gdrouet** [wuic/wuic#50]
``` css
.panel-loading {
  background: url('images/loading.gif') no-repeat 10px 10px;
}
```

with a group "easyui-css" will result int

``` css
.panel-loading {
  background: url('"/easyui-css//easyui/themes/c4/images/loading.gif") no-repeat 10px 10px;
}
```
